#!/usr/bin/env python3
"""Generate charset catalogs/case tables; verify TiKV-owned GB18030 overrides.

All modes verify the pinned Go 2094 pairs against TiKV's canonical 2103 pairs:
exactly the Go pairs plus nine explicit wire-only overrides, never a copied map.
``--gb-only`` updates only the generated include stub and removes the two exact,
hash-pinned obsolete native maps. ``--check-gb`` (alias ``--check``) verifies
that GB migration read-only; neither mode rewrites registry, case, or label data.
Normal mode also regenerates those non-GB outputs as before.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
from pathlib import Path
import re
import struct
import sys


ROOT = Path(__file__).resolve().parents[2]
CHARSET = ROOT / "pkg/parser/charset/charset.go"
GB18030 = ROOT / "pkg/parser/charset/encoding_gb18030_data.go"
GBK = ROOT / "pkg/parser/charset/encoding_gbk.go"
ENCODING_TABLE = ROOT / "pkg/parser/charset/encoding_table.go"
OUTPUT = ROOT / "rust/crates/tidb-datatype/src/charset_data.rs"
OUTPUT_DIR = ROOT / "rust/crates/tidb-datatype/src/charset_data"
ENCODING_OUTPUT = ROOT / "rust/crates/tidb-datatype/src/encoding_labels.rs"

GENERATED_HEADER = "// Generated by rust/scripts/generate-parser-charset.py; do not edit."
TIKV_ROOT = ROOT.parent / "tikv"
TIKV_GB18030 = Path("components/tidb_query_datatype/src/codec/collation/encoding/gb18030_data.rs")
GB18030_GO_SHA256 = "d620a5a0e124d135c21a152a5a4b476af847bbe78e0ee3fd70886941d2aceed8"
GB18030_TIKV_SHA256 = "0fe60b01bdfa12c6f25c46470deb8a25bd3c6da925c7f9b83a92329f6b5fcf9d"
# SHA256 of byte-key-sorted little-endian (u32 encoded, u32 rune) records.
GB18030_NATIVE_PAIRS_SHA256 = "35b0bfe4bda90a06a2a1a9dc24e7b3d480f99d72143d899d8183ac2821193c08"
WIRE_ONLY_OVERRIDES = {
    0xFD9C: 0xF92C,
    0xFD9D: 0xF979,
    0xFD9E: 0xF995,
    0xFD9F: 0xF9E7,
    0xFDA0: 0xF9F1,
    0xFE40: 0xFA0C,
    0xFE41: 0xFA0D,
    0xFE47: 0xFA18,
    0xFE49: 0xFA20,
}
OBSOLETE_GB_MAPS = {
    "gb18030_by_rune.rs": (54678, "7014eb275031b287c8ea3d481c27d80b0b52ad8a1b83b7cc3151f124d884103e"),
    "gb18030_by_bytes.rs": (54679, "5950acdb934a19adf2ba0712e8c85086cc36865749569328fdfed1737035901c"),
}
OLD_STUB_SHA256 = "81df4b0cc8d5e6e511e6cbb6462e1b3b045e5ebd8e60a4034a69e402c0782ba2"


def rust_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def pinned_source(path: Path, expected_hash: str) -> str:
    contents = path.read_bytes()
    if hashlib.sha256(contents).hexdigest() != expected_hash:
        raise ValueError(f"source-pinned SHA256 differs: {path}")
    return contents.decode("utf-8")


def verify_shared_gb18030(tikv_root: Path = TIKV_ROOT) -> str:
    go_source = pinned_source(GB18030, GB18030_GO_SHA256)
    go_body = go_source.split("\t}{\n", 1)[1].split("\n\t}", 1)[0]
    go_pattern = r"\{('(?:\\.|[^'])+'),\s*(0x[0-9A-Fa-f]+)\}\s*,?"
    native = [
        (int(encoded, 16), ord(ast.literal_eval(rune)))
        for rune, encoded in re.findall(go_pattern, go_body)
    ]
    if re.sub(go_pattern, "", go_body).strip():
        raise ValueError("unsupported Go GB18030 override entry")

    canonical = pinned_source(tikv_root / TIKV_GB18030, GB18030_TIKV_SHA256)
    body = canonical.split("pub const GB18030_TO_UNICODE: &[(u32, char)] = &[", 1)[1].split("];", 1)[0]
    pattern = r"\(0x([0-9A-Fa-f]+), '\\u\{([0-9A-Fa-f]+)\}'\),"
    shared = [(int(encoded, 16), int(rune, 16)) for encoded, rune in re.findall(pattern, body)]
    if re.sub(pattern, "", body).strip():
        raise ValueError("unsupported canonical GB18030 override entry")
    for label, rows, count in (("Go", native, 2094), ("TiKV", shared, 2103)):
        if len(rows) != count or len(dict(rows)) != count or len({rune for _, rune in rows}) != count:
            raise ValueError(f"{label} GB18030 overrides must contain {count} unique byte/rune pairs")
    if shared != sorted(shared):
        raise ValueError("canonical GB18030 overrides are not byte-key sorted")
    if dict(native).keys() & WIRE_ONLY_OVERRIDES.keys():
        raise ValueError("Go GB18030 overrides overlap the nine wire-only byte keys")
    if dict(shared) != dict(native) | WIRE_ONLY_OVERRIDES:
        raise ValueError("TiKV GB18030 overrides differ from Go plus the exact nine wire-only pairs")
    digest = hashlib.sha256()
    for row in sorted(native):
        digest.update(struct.pack("<II", *row))
    if digest.hexdigest() != GB18030_NATIVE_PAIRS_SHA256:
        raise ValueError("Go GB18030 native-pair SHA256 differs")
    return go_source


def generated_stub() -> str:
    return "\n".join([
        GENERATED_HEADER,
        "// Tables live in `charset_data/*.rs`, one file per table.",
        "",
        'include!("charset_data/known_charsets.rs");',
        'include!("charset_data/collations.rs");',
        'include!("charset_data/gbk_cases.rs");',
        'include!("charset_data/gb18030_cases.rs");',
    ]) + "\n"


def update_gb_outputs(check: bool) -> None:
    expected_stub = generated_stub().encode("utf-8")
    if OUTPUT.is_symlink() or (OUTPUT.exists() and not OUTPUT.is_file()):
        raise ValueError(f"refusing non-file or symlink generated stub: {OUTPUT}")
    current_stub = OUTPUT.read_bytes() if OUTPUT.exists() else None
    pending = []
    # Validate the entire exact old set before writing the stub or deleting maps.
    for name, (size, expected_hash) in OBSOLETE_GB_MAPS.items():
        path = OUTPUT_DIR / name
        if path.is_symlink():
            raise ValueError(f"refusing obsolete GB18030 map symlink: {path}")
        if not path.exists():
            continue
        if check:
            raise ValueError(f"obsolete native GB18030 map must be absent: {path}; use --gb-only")
        if not path.is_file():
            raise ValueError(f"refusing non-file obsolete GB18030 map: {path}")
        contents = path.read_bytes()
        if len(contents) != size or hashlib.sha256(contents).hexdigest() != expected_hash:
            raise ValueError(f"refusing modified obsolete GB18030 map: {path}")
        pending.append(path)
    if check:
        if current_stub != expected_stub:
            raise ValueError(f"generated charset include stub is stale: {OUTPUT}; use --gb-only")
        return
    if current_stub != expected_stub:
        if current_stub is not None and hashlib.sha256(current_stub).hexdigest() != OLD_STUB_SHA256:
            raise ValueError(f"refusing unexpected generated charset include stub: {OUTPUT}")
        OUTPUT.write_text(generated_stub(), encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)} (removed only the two native mapping includes)")
    for path in pending:
        path.unlink()
        print(f"pruned {path.relative_to(ROOT)}")


def case_ranges(text: str, marker: str) -> list[tuple[int, ...]]:
    block = text[text.index(marker) :]
    end = block.index("\n\t}")
    pattern = re.compile(
        r"CaseRange\{Lo: 0x([0-9A-Fa-f]+), Hi: 0x([0-9A-Fa-f]+), "
        r"Delta: \[unicode\.MaxCase\]rune\{(-?\d+), (-?\d+), (-?\d+)\}\}"
    )
    return [tuple(int(value, 16 if index < 2 else 10) for index, value in enumerate(match.groups())) for match in pattern.finditer(block[:end])]


def generate_non_gb_outputs(gb_text: str) -> None:
    charset_text = CHARSET.read_text(encoding="utf-8")
    constants = dict(
        re.findall(r"(?m)^\s*(Charset[A-Za-z0-9]+)\s*=\s*\"([^\"]+)\"", charset_text)
    )
    charset_pattern = re.compile(
        r"(?m)^\s*(Charset[A-Za-z0-9]+):\s*\{Name:\s*(Charset[A-Za-z0-9]+),\s*"
        r"Maxlen:\s*(\d+),\s*DefaultCollation:\s*\"([^\"]+)\",\s*"
        r"Desc:\s*\"([^\"]+)\""
    )
    charsets = [
        (constants[key], int(maxlen), default, description)
        for key, name, maxlen, default, description in charset_pattern.findall(charset_text)
        if key == name
    ]

    collations_block = charset_text.split("var collations = []*Collation{", 1)[1].split("\n}", 1)[0]
    collation_pattern = re.compile(
        r"\{(\d+),\s*\"([^\"]+)\",\s*\"([^\"]+)\",\s*"
        r"(true|false),\s*(\d+),\s*(PadSpace|PadNone)\}"
    )
    collations = [
        (int(identifier), charset, name, default == "true", int(sortlen), pad == "PadSpace")
        for identifier, charset, name, default, sortlen, pad in collation_pattern.findall(collations_block)
    ]

    gbk_cases = case_ranges(GBK.read_text(encoding="utf-8"), "var GBKCase")
    gb18030_cases = case_ranges(gb_text, "GB18030Case")

    # Each top-level table gets its own generated part file (the file's own
    # natural organization: one const table per charset/collation/case
    # concern), `include!`-d in table declaration order from the small
    # `charset_data.rs` stub so charset.rs's `include!("charset_data.rs")`
    # keeps working unchanged and every symbol keeps its original visibility.
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    known_charsets_lines = [GENERATED_HEADER, "", "pub(crate) const KNOWN_CHARSETS: &[StaticCharsetInfo] = &["]
    for name, maxlen, default, description in charsets:
        known_charsets_lines.append(
            f"    StaticCharsetInfo {{ name: {rust_string(name)}, default_collation: {rust_string(default)}, description: {rust_string(description)}, maxlen: {maxlen} }},"
        )
    known_charsets_lines.append("];")
    (OUTPUT_DIR / "known_charsets.rs").write_text("\n".join(known_charsets_lines) + "\n", encoding="utf-8")

    collations_lines = [GENERATED_HEADER, "", "pub(crate) const ALL_COLLATIONS: &[StaticCollationInfo] = &["]
    for identifier, charset, name, default, sortlen, pad_space in collations:
        collations_lines.append(
            f"    StaticCollationInfo {{ id: {identifier}, charset: {rust_string(charset)}, name: {rust_string(name)}, is_default: {str(default).lower()}, sortlen: {sortlen}, pad_space: {str(pad_space).lower()} }},"
        )
    collations_lines.append("];")
    (OUTPUT_DIR / "collations.rs").write_text("\n".join(collations_lines) + "\n", encoding="utf-8")

    def write_cases(filename: str, name: str, values: list[tuple[int, ...]]) -> None:
        cases_lines = [GENERATED_HEADER, "", f"pub(crate) const {name}: &[CaseRange] = &["]
        cases_lines.extend(
            f"    CaseRange {{ lo: 0x{lo:X}, hi: 0x{hi:X}, upper: {upper}, lower: {lower}, title: {title} }},"
            for lo, hi, upper, lower, title in values
        )
        cases_lines.append("];")
        (OUTPUT_DIR / filename).write_text("\n".join(cases_lines) + "\n", encoding="utf-8")

    write_cases("gbk_cases.rs", "GBK_CASES", gbk_cases)
    write_cases("gb18030_cases.rs", "GB18030_CASES", gb18030_cases)

    encoding_rows = re.findall(
        r'(?m)^\s*"([^"]+)":\s*\{.+,\s*"([^"]+)"\},$',
        ENCODING_TABLE.read_text(encoding="utf-8"),
    )
    assert len(encoding_rows) == 218
    encoding_lines = [
        "// Generated by rust/scripts/generate-parser-charset.py; do not edit.",
        "",
        "const ENCODING_LABELS: &[EncodingLabel] = &[",
    ]
    encoding_lines.extend(
        f"    EncodingLabel {{ label: {rust_string(label)}, canonical: {rust_string(canonical)} }},"
        for label, canonical in encoding_rows
    )
    encoding_lines.append("];")
    ENCODING_OUTPUT.write_text("\n".join(encoding_lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--gb-only", action="store_true",
        help="verify canonical GB18030 data, update only the stub, and prune exact old native maps",
    )
    mode.add_argument(
        "--check-gb", "--check", action="store_true",
        help="read-only GB authority/stub/obsolete-map check; does not check registry/case/label outputs",
    )
    parser.add_argument(
        "--tikv-root", type=Path, default=TIKV_ROOT,
        help=f"required canonical-data checkout (default: {TIKV_ROOT})",
    )
    args = parser.parse_args()
    try:
        gb_text = verify_shared_gb18030(args.tikv_root)
        update_gb_outputs(check=args.check_gb)
        if not args.check_gb:
            update_gb_outputs(check=True)
        if not args.gb_only and not args.check_gb:
            generate_non_gb_outputs(gb_text)
    except (OSError, ValueError, IndexError, TypeError, struct.error) as error:
        print(f"charset source verification failed: {error}", file=sys.stderr)
        return 1
    print(
        "verified TiKV-owned GB18030 overrides: exact Go 2094 pairs + nine wire-only pairs; "
        "source/canonical/native-pair SHA256; generated stub; obsolete native maps absent"
    )
    print(f"verified canonical GB18030 data at {args.tikv_root / TIKV_GB18030}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
