#!/usr/bin/env python3
"""Read fixed Git objects; generate M0 evidence, never product source or Cargo state.

The allowlist/classification is a reviewed static inventory, not an executable
coverage instrument. Signature acceptance and lexical test links do not prove
full domain coverage. Only coverage-baseline.json is generated by this script.
"""
from __future__ import annotations
import argparse
import collections
import hashlib
import json
from pathlib import Path
import re
import subprocess
import tomllib

ROOT = Path('/home/agent/tidb/expression-unification')
SHA = {'tidb': '364aef2bab5cc633ecb76a775ae8f36f86a6687d',
       'tikv': '548812e1ef57aef077a2062a9cc356640a6347f5'}
EXPR = 'rust/crates/tidb-expr/src/'
CACHE = {}

def git(repo, *args):
    return subprocess.check_output(['git', '-C', str(ROOT / repo), *args], text=True)

def source(path, repo='tidb'):
    key = repo, path
    if key not in CACHE:
        CACHE[key] = git(repo, 'show', SHA[repo] + ':' + path)
    return CACHE[key]

def files(prefix, repo='tidb'):
    return git(repo, 'ls-tree', '-r', '--name-only', SHA[repo], '--', prefix).splitlines()

def lex_mask(text, hide_strings):
    # Rust comments (including nested block comments), raw/byte/ordinary
    # strings, chars versus lifetimes. Offsets and line numbers are retained.
    chars=list(text)
    n=len(text)
    i=0
    def blank(a,b):
        for j in range(a,b):
            if chars[j]!='\n': chars[j]=' '
    while i<n:
        start=i
        if text.startswith('//',i):
            end=text.find('\n',i)
            i=n if end<0 else end
            blank(start,i)
        elif text.startswith('/*',i):
            depth=1; i+=2
            while i<n and depth:
                if text.startswith('/*',i): depth+=1; i+=2
                elif text.startswith('*/',i): depth-=1; i+=2
                else: i+=1
            blank(start,i)
        else:
            raw=re.match(r'(?:br|r)(#*)"',text[i:]) if text[i] in 'br' and (i==0 or not (text[i-1].isalnum() or text[i-1]=='_')) else None
            if raw:
                closing='"'+raw[1]
                end=text.find(closing,i+len(raw[0]))
                i=n if end<0 else end+len(closing)
                if hide_strings: blank(start,i)
            elif text[i]=='"':
                i+=1
                while i<n:
                    if text[i]=='\\': i+=2
                    elif text[i]=='"': i+=1; break
                    else: i+=1
                if hide_strings: blank(start,min(i,n))
            elif text[i]=="'":
                char=re.match(r"'(?:\\(?:u\{[0-9a-fA-F_]+\}|x[0-9a-fA-F]{2}|.)|[^'\\\n])'",text[i:])
                if char:
                    i+=len(char[0])
                    if hide_strings: blank(start,i)
                else: i+=1
            else: i+=1
    return ''.join(chars)

def clean_comments(text):
    return lex_mask(text,False)

def masked(text):
    return lex_mask(text,True)

def body(path, name, repo='tidb'):
    text = source(path, repo)
    mask = masked(text)
    start = re.search(r'\bfn\s+' + re.escape(name) + r'\s*(?:<[^\n]*>)?\s*\(', mask)
    if not start:
        raise ValueError((path, name))
    begin = mask.index('{', start.end())
    depth = 1
    end = begin + 1
    while depth:
        if mask[end] == '{': depth += 1
        elif mask[end] == '}': depth -= 1
        end += 1
    return text[begin:end], text[:begin].count('\n') + 1

ALIASES = {
    'ceiling': 'ceil', 'character_length': 'char_length', 'octet_length': 'length',
    'ucase': 'upper', 'lcase': 'lower', 'substr': 'substring', 'mid': 'substring',
    'power': 'pow', 'atan2': 'atan', 'day': 'dayofmonth', 'adddate': 'date_add',
    'subdate': 'date_sub', 'sha': 'sha1', 'schema': 'database',
    'session_user': 'user', 'system_user': 'user', 'current_date': 'curdate',
    'current_time': 'curtime', 'current_timestamp': 'now', 'localtime': 'now',
    'localtimestamp': 'now', 'json_memberof': 'json_member_of',
    'json_merge_preserve': 'json_merge', 'position': 'locate',
    'regexp': 'regexp_like', 'rlike': 'regexp_like',
    'isunknown': 'isnull', 'isnotunknown': 'isnull',
    'isnottrue': 'istrue', 'isnotfalse': 'isfalse',
    'ltrim_with': 'trim', 'rtrim_with': 'trim',
    'convert': 'convert_charset', 'convert_using': 'convert_charset',
    'to_binary': 'convert_charset', 'from_binary': 'convert_charset',
}

def canonical(name):
    name = name.lower()
    if name.startswith('cast_'): return 'cast'
    if name.startswith('date_add_'): return 'date_add'
    if name.startswith('date_sub_'): return 'date_sub'
    if name.startswith('getvar_'): return 'getvar'
    return ALIASES.get(name, name)

DISPATCH = {
    'func.rs': ['eval_func', 'eval_session_state', 'eval_func_values_in', 'eval_func_values'],
    'math_fn/mod.rs': ['dispatch', 'dispatch_values'],
    'time_fn/mod.rs': ['dispatch'],
    'builtin_ext/string2.rs': ['dispatch'],
    'builtin_ext/crypto.rs': ['dispatch', 'eval_aes_lazy'],
    'builtin_ext/info.rs': ['dispatch'],
    'builtin_ext/json/mod.rs': ['dispatch'],
    'builtin_ext/json2.rs': ['dispatch'],
    'builtin_ext/regexp.rs': ['dispatch'],
    'builtin_ext/compare2.rs': ['dispatch'],
    'builtin_ext/misc.rs': ['dispatch_in'],
    'builtin_ext/vec.rs': ['dispatch'],
    'scalar_function.rs': ['binary_op_for_name', 'unary_op_for_name', 'eval_by_signature'],
}
EXTRA_NAMES = set('nullif json_member_of json_sum_crc32 convert_using to_binary from_binary unaryplus isunknown isnotunknown isnottrue isnotfalse ltrim_with rtrim_with values getvar getvar_int getvar_uint getvar_real getvar_decimal getvar_time getvar_string'.split())

HOST = {
    'benchmark': 'Execution-control primitive repeatedly evaluates arbitrary children; not a pure value kernel.',
    'sleep': 'Session cancellation / wall-clock sleeping service.',
    'random_bytes': 'OS randomness.',
    'uuid': 'Clock/randomness/process state.', 'uuid_v4': 'OS randomness.', 'uuid_v7': 'Clock/randomness.',
    'database': 'Session current database.', 'current_user': 'Session authenticated identity.',
    'current_role': 'Session roles.', 'current_resource_group': 'Session resource group.',
    'user': 'Session connected identity.', 'connection_id': 'Session connection identity.',
    'found_rows': 'Session result history.', 'row_count': 'Session DML history.',
    'last_insert_id': 'Session previous/current statement insert-id state.',
    'version': 'Server/system variable.', 'tidb_version': 'Server build information.',
    'nextval': 'Sequence catalog mutation.', 'lastval': 'Sequence session state.',
    'setval': 'Sequence catalog mutation.', 'getparam': 'Prepared parameter binding.',
    'getvar': 'Session user variable binding.', 'setvar': 'Session user variable mutation.',
    'values': 'Current INSERT row binding.',
    'get_lock': 'Advisory-lock service.', 'release_lock': 'Advisory-lock service.',
    'is_free_lock': 'Advisory-lock service.', 'is_used_lock': 'Advisory-lock service.',
    'release_all_locks': 'Advisory-lock service.',
    'tidb_decode_key': 'Columns::tidb_decode_key callback, including host catalog/key metadata.',
    'tidb_is_ddl_owner': 'DDL-owner host property.',
    'tidb_current_tso': 'Transaction timestamp host property.',
    'charset': 'Frontend FieldType metadata, not value evaluation.',
    'collation': 'Frontend FieldType metadata, not value evaluation.',
    'coercibility': 'Frontend expression metadata, not value evaluation.',
}

def registry():
    text = source(EXPR + 'builtin_registry.rs')
    return {m[1]: {'min': int(m[2]), 'max': None if m[3] == 'None' else int(m[4]),
                    'line': text[:m.start(1)].count('\n') + 1}
            for m in re.finditer(r'^\s*\("([^"\n]+)",\s*(\d+),\s*(None|Some\((\d+)\))\),', text, re.M)}

def candidates():
    reg = registry()
    allowed = set(reg) | EXTRA_NAMES
    found = collections.defaultdict(list)
    for short, functions in DISPATCH.items():
        path = EXPR + short
        for fn in functions:
            block, first = body(path, fn)
            clean = clean_comments(block)
            for m in re.finditer(r'"([A-Za-z_][A-Za-z_0-9]*)"', clean):
                name = m[1].lower()
                if name not in allowed and not name.startswith('cast_'): continue
                line = first + clean[:m.start()].count('\n')
                item = {'name': name, 'path': path, 'symbol': fn, 'line': line}
                if item not in found[canonical(name)]: found[canonical(name)].append(item)
    return reg, found

# Manual additions are syntax / binding dispatches without a quoted SQL name.
MANUAL = {
    'between': [('lib.rs', 'eval_in', 1066), ('rewriter.rs', 'rewrite_leaf_compound', 1626)],
    'date_literal': [('time_literal.rs', 'date_literal', 124), ('rewriter.rs', 'rewrite_leaf_call', 2335)],
    'timestamp_literal': [('time_literal.rs', 'timestamp_literal', 184), ('rewriter.rs', 'rewrite_leaf_call', 2335)],
    'getvar': [('scalar_function.rs', 'eval_by_signature', 2001)],
}

CATEGORIES = {
    'operator_numeric': set('plus minus mul div intdiv mod unaryplus unaryminus bitand bitor bitxor bitneg leftshift rightshift'.split()),
    'comparison': set('eq ne lt le gt ge nulleq in between greatest least interval'.split()),
    'control': set('and or xor not isnull istrue istrue_with_null isfalse if ifnull coalesce nullif case'.split()),
    'math': set('abs acos asin atan ceil floor round truncate sign sqrt pow exp ln log log2 log10 pi sin cos tan cot radians degrees conv crc32 rand'.split()),
    'string': set('ascii bin bit_count bit_length char_func char_length concat concat_ws elt export_set field find_in_set format from_base64 hex insert_func instr left length locate lower lpad ltrim make_set oct ord quote repeat replace reverse right rpad rtrim space strcmp substring substring_index to_base64 translate trim unhex upper weight_string'.split()),
    'pattern': set('like ilike regexp_like regexp_instr regexp_replace regexp_substr'.split()),
    'temporal': set('addtime date date_add date_format date_sub datediff dayname dayofmonth dayofweek dayofyear extract from_days from_unixtime get_format hour last_day makedate maketime microsecond minute month monthname period_add period_diff quarter sec_to_time second str_to_date subtime tidb_parse_tso tidb_parse_tso_logical time time_format time_to_sec timediff timestamp timestampadd timestampdiff to_days to_seconds unix_timestamp week weekday weekofyear year yearweek convert_tz date_literal timestamp_literal now curdate curtime utc_timestamp utc_date utc_time sysdate tidb_bounded_staleness'.split()),
    'crypto': set('aes_encrypt aes_decrypt compress decode encode md5 password sha1 sha2 sm3 uncompress uncompressed_length validate_password_strength'.split()),
    'network': set('inet_aton inet_ntoa inet6_aton inet6_ntoa is_ipv4 is_ipv6 is_ipv4_compat is_ipv4_mapped'.split()),
    'misc': set('any_value name_const bin_to_uuid is_uuid uuid_timestamp uuid_to_bin uuid_version tidb_shard vitess_hash format_bytes format_nano_time tidb_decode_plan tidb_decode_binary_plan tidb_encode_sql_digest grouping load_file'.split()),
}

PROFILES = {
    'operator_numeric': {
        'type_domains': 'Typed Int (signed/unsigned), Real and Decimal numeric lanes; AST datum-driven coercions; bitwise/shift use integer conversion. Hybrid YEAR/BIT/ENUM/SET, numeric binary-literal provenance and NULL branches are overload facts, not interchangeable text.',
        'context_domains': ['division precision increment', 'NO_UNSIGNED_SUBTRACTION', 'overflow/truncation policy and diagnostic expression text', 'row versus vector warning order'],
        'collation_domains': 'Numeric lane itself is not collation-sensitive; string/hybrid casts and literal provenance still matter.',
        'sources': ['ops.rs', 'ops/operand.rs', 'ops/integer_coerce.rs', 'ops/real_coerce.rs', 'coerce.rs', 'scalar_function.rs', 'builtin_arithmetic.rs'],
    },
    'comparison': {
        'type_domains': 'Int signedness, Real, Decimal, String, Time/Duration, Json, VectorFloat32 and row-valued comparison routing are source-defined; not a claim that every pair is accepted by every operator. NULL-safe equality, IN NULL mask, typed GREATEST/LEAST and lazy INTERVAL are distinct domains.',
        'context_domains': ['derived collation/coercibility', 'typed comparison refinement', 'NULL and argument evaluation order', 'warning policy', 'IN constant cache versus dynamic candidates'],
        'collation_domains': 'String lanes use derived collator; AST value-only/default derivation differs. Legacy/new mode and all registered native collators are frozen obligations where reachable, not a proven Cartesian product.',
        'sources': ['ops.rs', 'row.rs', 'coerce.rs', 'builtin_compare.rs', 'builtin_ext/compare2.rs', 'scalar_function.rs', 'func.rs'],
    },
    'control': {
        'type_domains': 'Nullable truthiness and selected result Datum; typed control result is shaped by merged FieldType, while AST returns natural branch Datum. PB supported result types are enumerated per row, not assumed complete.',
        'context_domains': ['lazy/demand order per entrypoint', 'typed result shaping', 'warning/error timing', 'volatile/host child multiplicity'],
        'collation_domains': 'Selected string results retain inferred charset/collation; condition casts may be numeric.',
        'sources': ['func.rs', 'lib.rs', 'ops.rs', 'coerce.rs', 'scalar_function.rs', 'rewriter/control_type.rs'],
    },
    'math': {
        'type_domains': 'Numeric arguments through native numeric_arg/coercion; ABS/SIGN/CEIL/FLOOR/ROUND/TRUNCATE have source/result-type-specific integer/unsigned/real/decimal branches; transcendental functions use ETReal. Exact per-value bounds live in the referenced fixed source.',
        'context_domains': ['numeric-prefix truncation warnings', 'overflow diagnostics', 'declared decimal result scale', 'binary literal provenance for CONV'],
        'collation_domains': 'No comparison collation; string-to-number/bytes conversion remains source-sensitive.',
        'sources': ['math_fn/mod.rs', 'math_fn/go_exp_log.rs', 'math_fn/go_trig.rs', 'arg_eval_type.rs', 'scalar_function.rs'],
    },
    'string': {
        'type_domains': 'String/Bytes plus function-specific ETString/ETInt coercion; binary versus UTF8 unit signatures, optional position/length/locale, hybrid inputs, and malformed UTF8 handling differ by operation. NULL and packet-overflow paths are included.',
        'context_domains': ['max_allowed_packet', 'connection charset', 'derived versus input collation', 'argument cast policy', 'constant pattern/list cache where applicable'],
        'collation_domains': 'StrUnits byte versus rune selection is not collation equality. LOCATE/INSTR/STRCMP/FIELD/FIND_IN_SET/WEIGHT_STRING use appropriate collator; other operations preserve bytes or character semantics. See global collation catalog.',
        'sources': ['string_fn.rs', 'string_signature.rs', 'string_packet.rs', 'builtin_ext/string2.rs', 'build.rs', 'scalar_function.rs', 'arg_eval_type.rs', 'convert_charset.rs'],
    },
    'pattern': {
        'type_domains': 'Nullable sql_bytes/sql_string operands; LIKE/ILIKE escape byte, wildcard and invalid-octet behavior; REGEXP pattern, match type, optional position/occurrence/return option/replacement. Binary and Unicode domains are not assumed equivalent.',
        'context_domains': ['collation', 'statement context ID for cache', 'deferred pattern failure in unused branch', 'NULL/argument evaluation order'],
        'collation_domains': 'LIKE uses datum/default or derived collator and byte/rune mode; REGEXP derives match type from collation. All collation/pattern/input cross-products remain dynamically unverified.',
        'sources': ['like.rs', 'regexp.rs', 'builtin_ext/regexp.rs', 'scalar_function.rs', 'lib.rs'],
    },
    'temporal': {
        'type_domains': 'Typed Date/Datetime/Timestamp, Duration, string/numeric sources and source FieldType (especially YEAR); interval units, FSP and result shape selected by each function. AST often returns strings while typed paths parse computed Time/Duration. No universal timezone/zero-date/SQL-mode compatibility claim.',
        'context_domains': ['session timezone and DST', 'date SQL modes', 'default_week_format', 'statement date for duration conversions', 'warning/truncation level', 'FSP and interval-unit metadata'],
        'collation_domains': 'Temporal parsing/formatting generally textual rather than collator-based; source charset conversion still applies.',
        'sources': ['time_fn/mod.rs', 'time_fn/calendar.rs', 'time_fn/add_sub.rs', 'time_fn/duration_parse.rs', 'time_fn/convert_tz.rs', 'time_fn/session_tz.rs', 'time_fn/extract.rs', 'cast.rs', 'scalar_function.rs'],
    },
    'json': {
        'type_domains': 'BinaryJSON/document text, scalars, path expressions and typed SQL-to-JSON constructors; JSON null differs from SQL NULL; opaque binary-charset values exist on typed path. Each path wildcard/cardinality/error rule is source-defined. Full object/numeric/temporal domains are not inferred from dispatch.',
        'context_domains': ['source FieldType and binary charset', 'path/schema metadata caching keyed to statement', 'argument evaluation order', 'JSON_MERGE deprecation warning'],
        'collation_domains': 'JSON comparison/encoding is separate from SQL collator order; string-valued arguments still have charset/provenance.',
        'sources': ['builtin_ext/json/mod.rs', 'builtin_ext/json/path.rs', 'builtin_ext/json/value.rs', 'builtin_ext/json/construct.rs', 'builtin_ext/json/modify.rs', 'builtin_ext/json/merge.rs', 'builtin_ext/json/predicate.rs', 'builtin_ext/json/search.rs', 'builtin_ext/json/text.rs', 'builtin_ext/json/report.rs', 'builtin_ext/json2.rs', 'scalar_function.rs'],
    },
    'vector': {
        'type_domains': 'VectorFloat32 or native parsed textual vector according to function; dimensions and distance/norm overflow/NaN behavior are source-defined. Not a claim of all scalar-to-vector casts.',
        'context_domains': ['source dimensions', 'NULL/error handling'],
        'collation_domains': 'No vector comparator collation; textual conversion input is still a string domain.',
        'sources': ['builtin_ext/vec.rs', 'cast.rs'],
    },
    'cast': {
        'type_domains': 'One family containing all explicit/implicit casts: Signed, Unsigned, UnsignedInUnion, Char, Binary, Decimal, Date, DateTime, Year, Double, Float, Vector, Time, Json. Synthetic source-specific in-union names are overloads, not extra families; all PB source/target pairs listed separately.',
        'context_domains': ['source and full target FieldType flags/width/scale/FSP', 'inUnion', 'binary literal versus byte string', 'timezone/date modes', 'truncate/overflow policy', 'max_allowed_packet', 'connection charset'],
        'collation_domains': 'Binary/character targets differ in padding, truncation unit, encoding and errors. No Cartesian source-target matrix is certified.',
        'sources': ['cast.rs', 'func.rs', 'arg_eval_type.rs', 'scalar_function.rs', 'scalar_function/pb_builtin.rs', 'aggregation/wrap_cast.rs'],
    },
    'convert_charset': {
        'type_domains': 'Explicit CONVERT USING plus synthetic to_binary/from_binary. Legacy utf8/utf8mb4/ascii/latin1/binary bypass differs from nonlegacy encoding; explicit decode/replace and implicit error semantics differ.',
        'context_domains': ['declared source/target charset', 'binary provenance', 'derived result collation'],
        'collation_domains': 'Charset encode/decode, not SQL comparison; supported encoding catalog is distinct from collation catalog.',
        'sources': ['convert_charset.rs', 'scalar_function.rs', 'lib.rs', 'cast.rs'],
    },
    'crypto': {
        'type_domains': 'Byte-string coercion, digest/compression/encoding/AES variants; AES key-size/mode/IV and SHA2 length are overload axes. Password validation also consumes host configuration; that is explicitly mixed rather than dropping this family.',
        'context_domains': ['block_encryption_mode', 'AES lazy ignored-IV branch', 'warning policy', 'password policy/global vars and identities for validation'],
        'collation_domains': 'Binary-aware argument transcoding precedes byte kernels; collation comparison is not the digest algorithm.',
        'sources': ['builtin_ext/crypto.rs', 'go_flate.rs', 'convert_charset.rs'],
    },
    'network': {
        'type_domains': 'IPv4/IPv6 byte/text parsing, integer network-order conversion and NULL; exact malformed-string forms source-defined.',
        'context_domains': ['numeric cast warning policy for INET_NTOA'],
        'collation_domains': 'ASCII/byte format validation, not collator equality.',
        'sources': ['builtin_ext/compare2.rs'],
    },
    'misc': {
        'type_domains': 'Per-family deterministic value/metadata kernel: identity, UUID transforms, numeric formatting, TiDB-specific pure encoding/hash, or GROUPING mask with bound metadata. See dispatch/function extents for exact domain.',
        'context_domains': ['numeric conversion policy', 'GROUPING mode/mark metadata', 'source-specific warnings'],
        'collation_domains': 'Operation-specific; do not infer all collations from registration.',
        'sources': ['builtin_ext/misc.rs', 'builtin_ext/info.rs', 'grouping.rs', 'scalar_function.rs'],
    },
    'host': {
        'type_domains': 'Host primitive/binding; parameter and result types remain part of compatibility, but this family does not enter the pure-kernel denominator.',
        'context_domains': ['per-row/statement/session/request host state; see exclusion reason'],
        'collation_domains': 'Host values still retain full FieldType/charset/collation.',
        'sources': ['context.rs', 'func.rs', 'scalar_function.rs', 'time_fn/mod.rs'],
    },
}

NOTES = {
    'rand': 'Mixed: eval_rand_values dynamic-seed branch computes MysqlRng::new_with_seed(seed).gen() deterministically each row; constant seed uses per-occurrence mutable generator and unseeded consumes session RNG. Count family, migrate algorithm; host owns entropy/state identity and lifetime, not a duplicate RNG algorithm.',
    'now': 'Mixed: host supplies one statement instant; pure FSP parsing/rounding/timezone formatting remains counted. CURRENT_TIMESTAMP/LOCALTIME/LOCALTIMESTAMP variants retain exact argument/diagnostic semantics.',
    'curdate': 'Mixed: host statement instant plus pure session-local date extraction/formatting, all counted.',
    'curtime': 'Mixed: host instant plus pure FSP extraction; no-arg truncate differs from explicit-FSP round (microsecond truncation first).',
    'utc_timestamp': 'Mixed: host instant plus pure direct nanosecond half-up FSP rounding/UTC formatting.',
    'utc_date': 'Mixed: host instant plus pure UTC date extraction/formatting.',
    'utc_time': 'Mixed: host instant plus pure FSP/UTC duration formatting; explicit NULL differs from CURRENT_TIME.',
    'sysdate': 'Mixed: host live-clock read or statement NOW alias; pure FSP/timezone formatting counted; preserve call multiplicity.',
    'tidb_bounded_staleness': 'Mixed: host statement SafeTS binding; argument datetime parsing/clamping and return-shaping pure domain stays counted.',
    'and': 'AST eval_in eagerly evaluates both binary children; typed/PB Logic short-circuits. Preserve the discrepancy as baseline, do not assert current AST is lazy.',
    'or': 'AST eval_in eagerly evaluates both binary children; typed/PB Logic short-circuits.',
    'between': 'AST evaluates expr once and both comparison bounds; typed rewrite composes >=, <= and AND. Negated spelling is an overload, not another family.',
    'case': 'Simple/searched AST CASE evaluates selector once; typed rewrites to condition/result pairs. Result shaping and selector multiplicity require independent tests.',
    'nullif': 'AST/values dispatch compares already evaluated values; planner may rewrite or type it differently. Do not infer multiplicity from family name.',
    'unix_timestamp': 'Mixed: zero-argument form consumes statement clock (host domain); one-argument conversion is a pure contextual kernel and keeps the entire logical family in denominator.',
    'json_schema_valid': 'Mixed: local schema validation is pure; external $ref uses HTTP(S)/file retrieval in LocalSchemaRetriever. Family remains denominator; host retrieval must be separately bound/deferred, not silently disabled.',
    'validate_password_strength': 'Mixed pure policy checks + host global vars/current/login identity. Retained in denominator conservatively; do not later reclassify it wholesale as host to improve coverage.',
    'json_sum_crc32': 'Native values/AST Expr::Func callable helper for homogeneous scalar arrays; SQL JsonSumCrc32 ARRAY cast syntax is explicitly rejected. Do not claim typed ARRAY support.',
    'date_literal': 'Computed during rewrite via time_literal::date_literal, not ordinary CAST; direct eval_in rejects typed literal styles. Regex/hard-error/date-mode semantics are migration obligations.',
    'timestamp_literal': 'Computed during rewrite via time_literal::timestamp_literal, not ordinary CAST; direct eval_in rejects typed literal styles. Offset/timezone/FSP/hard-error semantics are migration obligations.',
    'cast': 'Vector source permits only Char/Binary/Vector in eval_cast. Array casts unsupported. TimeLiteral rewrite currently falls through ordinary cast whereas direct AST rejects it; no separate dedicated TimeLiteral kernel claimed.',
    'atan': 'ATAN one/two-argument forms and ATAN2 two-argument spelling are one logical family; preserve both arity/argument-order domains.',
    'json_merge': 'JSON_MERGE_PRESERVE is the same value operation, but JSON_MERGE emits deprecation warning after successful non-NULL result. Alias normalization does not erase the warning obligation.',
    'regexp_like': 'REGEXP/RLIKE operator and REGEXP_LIKE are one predicate family; optional match_type and differing wrapper/cast paths remain distinct overloads.',
    'locate': 'POSITION syntax normalizes to LOCATE; INSTR remains a separate family (argument order differs).',
    'trim': 'Both/Leading/Trailing remstr variants incl. ltrim_with/rtrim_with share TRIM grammar family; one-argument LTRIM/RTRIM remain separate functions.',
    'load_file': 'Native unconditional SQL NULL behavior, not implemented filesystem access. Listed compatibility stub, excluded from pure-kernel denominator and migration numerator.',
    'grouping': 'Pure metadata mask computation is included; planner Expand/grouping ownership is not migrated wholesale.',
    'istrue': 'IS NOT TRUE is a syntactically negated variant; istrue_with_null is a separately counted NULL-preserving family.',
    'isfalse': 'IS NOT FALSE is a syntactically negated variant, not an extra family.',
    'isnull': 'IS UNKNOWN is an alias; IS NOT NULL/UNKNOWN negate the same test rather than creating a new kernel family.',
}

AST_FORMS = {
    'binary': {'family_ids': sorted(CATEGORIES['operator_numeric'] | CATEGORIES['comparison'] | {'and','or','xor'}), 'source': 'lib.rs:886-920', 'notes': 'Row comparisons are comparison overloads, not a ROW scalar result.'},
    'unary': {'family_ids': ['unaryplus','unaryminus','bitneg','not'], 'source': 'lib.rs:879-880'},
    'in_list': {'family_ids': ['in'], 'source': 'lib.rs:1065; func.rs::eval_in_list'},
    'between': {'family_ids': ['between'], 'source': 'lib.rs:1066-1084'},
    'is': {'family_ids': ['isnull','istrue','isfalse'], 'source': 'lib.rs:1085-1094'},
    'like': {'family_ids': ['like','ilike'], 'source': 'lib.rs:1095-1131'},
    'regexp': {'family_ids': ['regexp_like'], 'source': 'lib.rs:1138-1150'},
    'case': {'family_ids': ['case'], 'source': 'lib.rs:1218-1277'},
    'cast': {'family_ids': ['cast'], 'source': 'lib.rs:995-1014'},
    'convert_using': {'family_ids': ['convert_charset'], 'source': 'lib.rs:1020-1054'},
    'extract': {'family_ids': ['extract'], 'source': 'lib.rs:930-932'},
    'timestamp_add': {'family_ids': ['timestampadd'], 'source': 'lib.rs:939-957'},
    'timestamp_diff': {'family_ids': ['timestampdiff'], 'source': 'rewriter.rs:1965', 'notes': 'Dedicated syntax is rewritten; no direct eval_in Expr::TimestampDiff arm.'},
    'member_of': {'family_ids': ['json_member_of'], 'source': 'rewriter.rs:1807', 'notes': 'Dedicated syntax is rewritten; no direct eval_in Expr::MemberOf arm.'},
    'get_format': {'family_ids': ['get_format'], 'source': 'lib.rs:962-975'},
    'weight_string': {'family_ids': ['weight_string'], 'source': 'lib.rs:1159-1187'},
    'position': {'family_ids': ['locate'], 'source': 'lib.rs:1188-1191; rewriter.rs:1924'},
    'trim': {'family_ids': ['trim'], 'source': 'lib.rs:1192-1217'},
    'typed_literals': {'family_ids': ['date_literal','timestamp_literal','cast'], 'source': 'rewriter.rs:2335-2427', 'notes': 'Direct AST rejects all three styles; Date/Timestamp have dedicated rewrite computations; Time falls through cast.'},
    'ordinary_leaves': {'family_ids': [], 'source': 'lib.rs:797-879', 'notes': 'Constants, column binding, parens, charset/collation annotation do not inflate family denominator.'},
    'row': {'family_ids': ['eq','ne','lt','le','gt','ge','nulleq','in'], 'source': 'row.rs; rewriter.rs:891-984,1439,2529', 'notes': 'Structural carrier expanded for row comparison/IN; standalone ROW has no scalar evaluator.'},
    'fts_fallback': {'family_ids': ['ilike','ifnull','not','and','or'], 'source': 'fts.rs::build_fts_to_ilike_expression', 'notes': 'Fallback composition is not another native full-text kernel; FTS_MATCH_WORD/MATCH_AGAINST native evaluators are not implemented.'},
}

UNIMPLEMENTED = {
    'fts_match_word': ('no_native_kernel_with_lowering_subset', 'builtin_registry.rs:491-495 rejects native evaluator; fts.rs builds ILIKE fallback composition.'),
    'match_against': ('no_native_kernel_with_lowering_subset', 'builtin_registry.rs:496-500 rejects native evaluator; gated session/planner fallback has existing tests.'),
    'uuid_short': ('source_deliberately_unavailable', 'builtin_registry.rs:484 returns FunctionNotExists; not a migrated kernel.'),
    'tidb_decode_sql_digests': ('never_implemented_at_baseline', 'Registry-only, no executable dispatch/lowering found in Rust crates; fallback unresolved_error is Unsupported.'),
    'tidb_encode_index_key': ('never_implemented_at_baseline', 'Registry-only, no executable dispatch/lowering found in Rust crates.'),
    'tidb_encode_record_key': ('never_implemented_at_baseline', 'Registry-only, no executable dispatch/lowering found in Rust crates.'),
    'tidb_mvcc_info': ('never_implemented_at_baseline', 'Registry-only, no executable dispatch/lowering found in Rust crates.'),
    'tidb_row_checksum': ('never_implemented_at_baseline', 'Registry-only, no executable dispatch/lowering found in Rust crates.'),
    'row': ('structural_only', 'rewriter.rs:2529 constructs row carrier, comparisons expand it; no standalone scalar result.'),
    "'tidb`.(dateliteral": ('syntax_lowered', 'date_literal family via CastStyle::DateLiteral; no name-dispatch kernel for internal registry spelling.'),
    "'tidb`.(timestampliteral": ('syntax_lowered', 'timestamp_literal family via CastStyle::TimestampLiteral.'),
    "'tidb`.(timeliteral": ('syntax_lowered_with_distinct_gap', 'TimeLiteral rewriter falls through cast_time; direct eval_in rejects it and no dedicated native time-literal validator exists.'),
}

DELETION_MAP = [
    {'id':'ast_dispatch','paths':[EXPR+'lib.rs',EXPR+'func.rs'], 'delete':'Migrated eval_in arms, eval_func/eval_func_values computations; native helper algorithms apply_binary/apply_unary/date_add_interval/concat_values/avg_of*/fit_decimal_column delegate shared primitives.', 'retain':'Public compatibility signatures, AST binding/lowering, host/session dispatch and literal representation; do not remove whole lib.rs.'},
    {'id':'typed_dispatch','paths':[EXPR+'scalar_function.rs'], 'delete':'Migrated eval_by_signature arms; eval_fast_integer_binary; eval_numeric_row/operand arithmetic; CompareValue::cmp, vec_eval_bool, eval_integer_batch/eval_arithmetic_batch computations, cached native pattern/path computation.', 'retain':'Node identity/schema/FieldType/hash/clone/decorrelation, compiled-state invalidation and representation adaptation; no duplicate numeric fallback.'},
    {'id':'pb_kernel','paths':[EXPR+'scalar_function/pb_builtin.rs',EXPR+'distsql_builtin.rs'], 'delete':'All migrated Kernel computation branches (Binary, Logic, IntegerMod, IsNull, Truth, Case, If, IfNull, Cast, String, Round, FromUnixTime, Regexp, Json, Values).', 'retain':'Exact wire signature and complete wire FieldType; PB decoding, argument signedness versus wire result interpretation and tests.'},
    {'id':'native_ops_cast','paths':[EXPR+x for x in ['ops.rs','ops/integer_coerce.rs','ops/real_coerce.rs','coerce.rs','cast.rs','arg_eval_type.rs','row.rs','binary_literal.rs']], 'delete':'Migrated arithmetic/comparison/boolean/cast/coercion algorithms across helper and SQL/PB consumers.', 'retain':'Operand provenance/type decisions and argument-lowering policy where distinct from value computation; range/sentinel host representation.'},
    {'id':'native_families','paths':[EXPR+x for x in ['math_fn/','string_fn.rs','string_signature.rs','string_packet.rs','time_fn/','time_literal.rs','like.rs','regexp.rs','convert_charset.rs','builtin_ext/','go_flate.rs','grouping.rs']], 'delete':'Each migrated pure kernel and its now-unused native helper/metadata executor. Include crypto, ordinary JSON/time/vector and TiDB-specific pure kernels, not only registry-common math.', 'retain':'Explicit host-only functions and narrowly registered host domains; parser/type builder/context binding separate from algorithms; no whole-module deletion when mixed.'},
    {'id':'batch_filter','paths':[EXPR+'evaluator.rs','rust/crates/tidb-executor/src/selection.rs'], 'delete':'Migrated bool/Decimal/numeric vector kernels and FastSelectionFilter NullTest/StringIn/And native predicate computations.', 'retain':'Selection/null-mask scheduling, EQ-from-IN handling, logical/physical row order, ColumnSwapHelper, per-worker EvaluatorSuite lifecycle; FastSelectionFilter is nonbatched path only.'},
    {'id':'unistore_native','paths':['rust/crates/tidb-unistore/src/cophandler.rs','rust/crates/tidb-unistore/src/cophandler/'], 'delete':'Migrated SimpleSig arms in eval_expr/eval_datum and eval_* helpers, including shadowed legacy variants. Replace convert_expr_with_context admission before removing code.', 'retain':'DAG/TopN/aggregation scheduling, request Columns/context, row/FieldType decoding, one warning sink/drain and host storage ownership.'},
    {'id':'shared_primitives','paths':['rust/crates/tidb-datatype/src/collation.rs','rust/crates/tidb-datatype/src/decimal/mod.rs','rust/crates/tidb-datatype/src/mydecimal.rs','rust/crates/tidb-datatype/src/datum/compare.rs','rust/crates/tidb-datatype/src/datum/convert.rs','rust/crates/tidb-datatype/src/datum_convert.rs','rust/crates/tidb-datatype/src/binary_json_ops.rs','rust/crates/tidb-datatype/src/time_parse.rs','rust/crates/tidb-datatype/src/mysql_time.rs','rust/crates/tidb-datatype/src/duration.rs'], 'delete':'Duplicate migrated comparison/key/LIKE, Decimal operations, cast/value, temporal/JSON kernels as domains close; hash/index encoding needs independent compatibility proof.', 'retain':'Full SQL FieldType/schema, storage codec/Chunk layout, metadata and representation wrappers; collation deferred domains explicitly remain.'},
    {'id':'construction_and_consumers','paths':[EXPR+x for x in ['constant_fold.rs','constant.rs','build.rs','builtin_arithmetic.rs','builtin_compare.rs','rewriter.rs','rewriter/','new_function.rs','pushdown_catalog.rs']], 'delete':'Only computation that would bypass shared evaluator after migration; folding computes via shared entrypoint.', 'retain':'Arity/type inference/collation derivation, fold policy and TryFold rollback, remote pushdown admission/blacklist/serialization; never delete whole planner/executor state machines.'},
]

# Entrypoints are source call-graph evidence, not runtime origin assertions.
ENTRYPOINTS = [
    {'id':'ast','path':EXPR+'lib.rs','symbols':['eval','eval_in'], 'status':'native','obligation':'Direct AST/session caller must lower without invoking rewrite-fold-eval recursion; retain no-schema API limitations.'},
    {'id':'typed_row','path':EXPR+'expression.rs','symbols':['Expression::eval'], 'status':'native','obligation':'ScalarFunction::eval PB-first, then fast integer/native dispatch; Column/Constant/Correlated are bindings.'},
    {'id':'pb_typed','path':EXPR+'distsql_builtin.rs','symbols':['pb_to_expr','supports_signature'], 'status':'native','obligation':'Typed Kernel, signature independent of display function name.'},
    {'id':'batch','path':EXPR+'evaluator.rs','symbols':['EvaluatorProgram','EvaluatorSuite','ColumnSwapHelper'], 'status':'native','obligation':'vec_eval_bool, vec_eval_decimal_arithmetic and try_eval_numeric_batch all bypass ordinary row computation.'},
    {'id':'filter','path':'rust/crates/tidb-executor/src/selection.rs','symbols':['SelectionExec','FastSelectionFilter'], 'status':'native','obligation':'FastSelectionFilter nonbatched row path; batched vectorized_filter_consider_null maintains EQ-from-IN null masks and physical selection.'},
    {'id':'helper','path':EXPR+'lib.rs','symbols':['eval_expression_once','apply_binary','apply_binary_with_div_precision','apply_unary','date_add_interval','concat_values','avg_of','avg_of_with_div_precision','fit_decimal_column','get_time_value'], 'status':'native','obligation':'Public value helpers and aggregate/window shared arithmetic cannot remain native aliases.'},
    {'id':'fold','path':EXPR+'constant_fold.rs','symbols':['fold_constant_in_mode'], 'status':'native','obligation':'Planner/constant/deferred/default/generated folds compute through same kernel owner, with warning rollback and bind-time semantics.'},
    {'id':'unistore','path':'rust/crates/tidb-unistore/src/cophandler.rs','symbols':['convert_expr_with_context','eval_expr','eval_datum','SimpleExpr::Shared','SimpleExpr::Func'], 'status':'native','obligation':'Shared context path is not enough; SimpleSig-only wire IDs keep native computations. Shared-supported parents cannot currently accept SimpleSig-only child trees.'},
]

ENTRYPOINTS.extend([
    {'id':'scan_filter','path':'rust/crates/tidb-executor/src/predicate_pushdown.rs','symbols':['FastScanFilter::StringIn','FastScanFilter::Like','PushedScanFilter::matches'], 'lines':'247-264,362-378,610-715','obligation':'Independent key-hash membership and like_match_with_collation bypass; not SelectionExec FastSelectionFilter.'},
    {'id':'vector_group_checker','path':'rust/crates/tidb-executor/src/vec_group_checker.rs','symbols':['split_into_groups','eval_group_item'],'lines':'104-176,439-457','obligation':'Direct try_eval_numeric_batch outside projection, with boundary-first row ordering.'},
    {'id':'projection_expand','path':'rust/crates/tidb-executor/src/projection.rs','symbols':['ProjectionExec'],'lines':'140-141,295-303,381-383','additional_sources':['rust/crates/tidb-executor/src/expand.rs:54-57,100-105'],'obligation':'Immutable program shared; execution/worker-local suite. Preserve swaps and virtual rows.'},
    {'id':'default_generated_check_partition','path':'rust/crates/tidb-executor/src/column_default.rs','symbols':['build_in_context','evaluate'],'lines':'715-733,832-862','additional_sources':['rust/crates/tidb-executor/src/generated_column.rs:454-474,510-552','rust/crates/tidb-executor/src/union_scan.rs:601-612','rust/crates/tidb-executor/src/kv_table.rs:2242-2297','rust/crates/tidb-executor/src/partition_routing.rs:403-410','rust/crates/tidb-executor/src/partition_pruning.rs:647-670','rust/crates/tidb-exec/src/table_info_build.rs:2078-2097'],'obligation':'Bind current session/dependency slots and preserve NULL CHECK policy; keep storage conversion separate.'},
    {'id':'dml','path':'rust/crates/tidb-executor/src/driver/dml.rs','symbols':['PreparedInsertValue::Expression','order_rows_for_dml','UpdateRowEvaluator::compute'],'lines':'867-881,1586-1631,3560-3614','additional_sources':['rust/crates/tidb-executor/src/driver/dml/correlated.rs:83-100,123-146'],'obligation':'Prepare once, rebind rows/parameters; correlated subquery host executes then binds value. Preserve assignment original-row semantics.'},
    {'id':'join','path':'rust/crates/tidb-executor/src/joiner.rs','symbols':['eval_bool','filter_inner','filter_and_check_inner'],'lines':'198-215,323-335,408-424','additional_sources':['rust/crates/tidb-executor/src/hash_join_v2.rs:1126-1162','rust/crates/tidb-executor/src/base_join_probe.rs:258','rust/crates/tidb-executor/src/apply/native.rs:211,253','rust/crates/tidb-executor/src/join/index_hash.rs:443'],'obligation':'CNF order, EQ-from-IN unknown mask, vector predicate and per-probe-worker context.'},
    {'id':'aggregate_window_args','path':'rust/crates/tidb-executor/src/hash_agg.rs','symbols':['eval_agg_input'],'lines':'3567-3674','additional_sources':['rust/crates/tidb-executor/src/hash_agg/input.rs:579-590','rust/crates/tidb-executor/src/hash_agg/group_key.rs:159-166','rust/crates/tidb-executor/src/stream_agg.rs:149-159,239-253','rust/crates/tidb-executor/src/window.rs:259-267,344-389,571-604','rust/crates/tidb-executor/src/hash_agg/window_numeric.rs:108-137','rust/crates/tidb-executor/src/shuffle.rs:361-377'],'obligation':'Arguments/order/group/frame/default expressions plus shared SUM/AVG arithmetic; not entire state-machine migration.'},
    {'id':'sort_materialization','path':'rust/crates/tidb-executor/src/sort.rs','symbols':['eval_sort_key','validate_by_items','compare_rows'],'lines':'280-313,364-398','additional_sources':['rust/crates/tidb-executor/src/driver/physical_builder.rs:1511-1562'],'obligation':'Sort directly admits columns/constants and does NOT evaluate constant values; noncolumn local TopN keys projected first. Preserve type comparison semantics.'},
    {'id':'planner_eval','path':'rust/crates/tidb-planner/src/plan_builder.rs','symbols':['fold_constant'],'lines':'1128-1164','additional_sources':['rust/crates/tidb-planner/src/ranger/points.rs:521-552','rust/crates/tidb-planner/src/physical_plan_cache.rs:331-345','rust/crates/tidb-planner/src/logical/rewrite.rs:3207-3217,3566-3576','rust/crates/tidb-executor/src/driver/planner_bridge.rs:2517-2532','rust/crates/tidb-executor/src/driver/catalog.rs:3067-3072','rust/crates/tidb-expr/src/expr_util/fold.rs:91-168,235','rust/crates/tidb-expr/src/expr_util/substitute.rs:740-746'],'obligation':'Fold warning stash/rollback/deferred evaluation belong to host policy; computation must share backend.'},
    {'id':'session_ast_and_binding','path':'rust/crates/tidb-session/src/show.rs','symbols':['show_row_matches'],'lines':'508-529','additional_sources':['rust/crates/tidb-session/src/variables.rs:1166-1201','rust/crates/tidb-session/src/prepared_ast.rs:482-528','rust/crates/tidb-session/src/warnings.rs:209-231','rust/crates/tidb-session/src/dispatch.rs:1178-1208'],'obligation':'SHOW directly invokes AST; SET runs SELECT, not direct AST here. Refresh cached-plan bindings and drain warnings at real boundaries.'},
    {'id':'helper_consumers','path':'rust/crates/tidb-exec/src/multi_statement_transaction.rs','symbols':['selection_matches_staged_row'],'lines':'1151-1185','additional_sources':['rust/crates/tidb-exec/src/aggregate/runtime/avg.rs:104-154','rust/crates/tidb-exec/src/aggregate/runtime/mod.rs:84-91'],'obligation':'apply_binary and avg_of_with_div_precision are public computation, including legacy consumers. No assertion every exported helper has a live SQL caller.'},
])
DELETION_MAP[5]['paths'].extend(['rust/crates/tidb-executor/src/predicate_pushdown.rs','rust/crates/tidb-executor/src/vec_group_checker.rs'])
DELETION_MAP[5]['delete'] += ' Also FastScanFilter::StringIn/Like and vec_group_checker numeric batch shortcut.'
DELETION_MAP.append({'id':'rng_and_clock_subkernels','paths':['rust/crates/tidb-util/src/mathutil/rand.rs',EXPR+'math_fn/mod.rs',EXPR+'time_fn/mod.rs',EXPR+'time_fn/add_sub.rs'], 'delete':'Duplicate seed-to-RNG transition, FSP rounding, clock/date/time formatting and staleness clamp calculations after equivalent shared primitives exist.', 'retain':'Host entropy, statement/live clock, SafeTS acquisition and generator instance lifetime; mixed counted family is not wholly host-exempt.'})

TEST_FILTERS = [
    ('tidb-expr','lib','evaluator::tests::',18),('tidb-expr','lib','constant::tests::',16),('tidb-expr','lib','constant_fold::deferred_function_tests::',8),('tidb-expr','lib','distsql_builtin::tests::',7),('tidb-expr','all','',18),
    ('tidb-executor','lib','projection::tests::',9),('tidb-executor','lib','selection::tests::',7),('tidb-executor','lib','predicate_pushdown::tests::',5),('tidb-executor','lib','vec_group_checker::tests::',25),('tidb-executor','lib','expand::tests::',3),
    ('tidb-executor','lib','column_default::tests::',8),('tidb-executor','lib','generated_column::tests::',7),('tidb-executor','lib','driver::tests::dml::',9),('tidb-executor','lib','driver::tests::column_defaults::',11),('tidb-executor','lib','joiner::tests::',19),('tidb-executor','lib','hash_agg::tests::',41),('tidb-executor','lib','stream_agg::tests::',6),('tidb-executor','lib','partition_pruning::tests::',19),
    ('tidb-executor','all','window_executor_source::',13),('tidb-executor','all','default_on_update_source::',6),('tidb-planner','all','core_expression_eval_source::',11),
    ('tidb-session','lib','tests_eval_bool::',3),('tidb-session','lib','tests_in_list_full_evaluation::',6),('tidb-session','lib','tests_prepared_plan_cache::',46),('tidb-session','lib','tests_generated_columns::',25),('tidb-session','lib','tests_window::',68),('tidb-session','all','expression_default_fold_source::',2),
    ('tidb-unistore','lib','cophandler::eval_context::tests::',5),('tidb-unistore','lib','cophandler::tests::',None),
    ('tidb_query_datatype','lib','codec::collation::',8),('tidb_query_expr','lib','impl_like::tests::',4),('tidb_query_expr','lib','short_circuit',16),('tidb_query_expr','lib','impl_control::tests::',4),('tidb_query_expr','lib','impl_compare_in::tests::',5),('tidb_query_expr','lib','impl_regexp::tests::',4),('tidb_query_expr','lib','impl_cast::tests::',79),
]

def test_commands():
    result=[]
    for package,target,filter_,count in TEST_FILTERS:
        tikv=package.startswith('tidb_query_')
        binary='cargo' if tikv else '/home/agent/tidb/expression-unification/tools/cargo-tidb'
        command=binary+' test --locked -p '+package+(' --lib ' if target=='lib' else ' --test '+target+' ')+filter_+' -- --test-threads=1'
        result.append({'working_directory':str(ROOT/('tikv' if tikv else 'tidb/rust')),'command':command,'literal_test_declarations':count,'execution':'proposed_not_run_by_Validation_E','caveat':'Static counts do not enumerate runtime/macro/cfg/ignored cases; planner core expression includes one ignored.'})
    return result

def profile(name):
    if name in HOST: return 'host'
    if name == 'cast': return 'cast'
    if name == 'convert_charset': return name
    if name.startswith('json_'): return 'json'
    if name.startswith('vec_'): return 'vector'
    for category, members in CATEGORIES.items():
        if name in members: return category
    raise ValueError('Unclassified family: ' + name)

def pb_family(sig):
    if sig.startswith('Cast'): return 'cast'
    for prefix, family in [
        ('AddDate','date_add'),('SubDate','date_sub'),('CaseWhen','case'),('IfNull','ifnull'),('If','if'),
        ('IntDivide','intdiv'),('Multiply','mul'),('Plus','plus'),('Minus','minus'),('Divide','div'),('Mod','mod'),
        ('NullEQ','nulleq'),('NullEq','nulleq'),('Eq','eq'),('Ne','ne'),('Lt','lt'),('Le','le'),('Gt','gt'),('Ge','ge'),
        ('InString','in'),('InInt','in'),('LikeSig','like'),('LogicalAnd','and'),('LogicalOr','or'),('LogicalXor','xor'),
        ('UnaryNot','not'),('CharLength','char_length'),('Upper','upper'),('Lower','lower'),('Substring','substring'),
        ('Atan','atan'),('Round','round'),('DateDiff','datediff'),('DateFormat','date_format'),
        ('WeekWithoutMode','week'),('TimestampDiff','timestampdiff'),('UnixTimestamp','unix_timestamp'),('FromUnixTime','from_unixtime'),
        ('RegexpLike','regexp_like'),('JsonMemberOf','json_member_of'),('JsonReplace','json_replace'),
        ('JsonArrayAppend','json_array_append'),('JsonMergePatch','json_merge_patch')]:
        if sig.startswith(prefix): return family
    if sig.endswith('IsNull'): return 'isnull'
    if sig.endswith('IsTrueWithNull'): return 'istrue_with_null'
    if sig.endswith('IsTrue'): return 'istrue'
    if sig.endswith('IsFalse'): return 'isfalse'
    mapping = {'MicroSecond':'microsecond'}
    return mapping.get(sig, canonical(re.sub(r'(?<!^)([A-Z])', r'_\1', sig).lower()))

def signatures():
    pbpath = EXPR + 'scalar_function/pb_builtin.rs'
    constructor, start = body(pbpath, 'new')
    pb = {}
    for match in re.finditer(r'^\s*([A-Z]\w*(?:\s*\|\s*[A-Z]\w*)*)\s*=>', clean_comments(constructor), re.M):
        for sig in re.findall(r'\b[A-Z]\w*\b', match[1]):
            pb[sig] = {'line':start+constructor[:match.start(1)].count('\n'), 'family':pb_family(sig)}
    casts, start = body(pbpath, 'cast_types')
    for match in re.finditer(r'\b(Cast\w+)\s*=>\s*\(EvalType::(\w+), EvalType::(\w+)\)', casts):
        pb[match[1]] = {'line':start+casts[:match.start()].count('\n'), 'family':'cast', 'source_eval_type':match[2], 'target_eval_type':match[3]}
    nativepath = 'rust/crates/tidb-unistore/src/cophandler.rs'
    converter, start = body(nativepath, 'convert_expr_with_context')
    native = {}
    for match in re.finditer(r'tipb::ScalarFuncSig::(\w+)\s*=>', clean_comments(converter)):
        sig = match[1]
        native[sig] = {'line':start+converter[:match.start()].count('\n'), 'family':pb_family(sig),
                       'routing':'shadowed_by_shared' if sig in pb else 'native_SimpleSig',
                       'implementation_status':'explicit_None_result_gap' if 'Duration' in sig and sig.endswith('Datetime') else 'dispatch_branch_present_domain_unverified'}
    assert len(pb) == 129, len(pb)
    assert len(native) == 218, len(native)
    return pb, native

def production_text(text):
    # Inline cfg(test) modules may occur in the middle of a production file.
    # Blank only those balanced modules, not everything after the first test.
    mask = masked(text)
    spans = []
    for m in re.finditer(r'#\[cfg\(test\)\]\s*(?:pub\s+)?mod\s+\w+\s*\{', mask):
        depth, end = 1, m.end()
        while depth:
            if mask[end]=='{': depth += 1
            elif mask[end]=='}': depth -= 1
            end += 1
        spans.append((m.start(),end))
    for start,end in reversed(spans):
        text = text[:start]+re.sub(r'[^\n]',' ',text[start:end])+text[end:]
    return text

def source_inventory():
    include = ['lib.rs','func.rs','scalar_function.rs','scalar_function/pb_builtin.rs','ops.rs','ops/','cast.rs','coerce.rs','arg_eval_type.rs','math_fn/','string_fn.rs','string_signature.rs','string_packet.rs','like.rs','regexp.rs','time_fn/','time_literal.rs','builtin_ext/','convert_charset.rs','grouping.rs','row.rs','go_flate.rs','evaluator.rs']
    result = []
    for path in files(EXPR):
        relative = path[len(EXPR):]
        if not path.endswith('.rs') or not any(relative == p or (p.endswith('/') and relative.startswith(p)) for p in include): continue
        if '/tests' in relative or relative.endswith('_tests.rs'): continue
        text = source(path)
        production = production_text(text)
        symbols = [{'name':m[1], 'line': production[:m.start()].count('\n')+1}
                   for m in re.finditer(r'\bfn\s+(\w+)\s*(?:<[^\n]*>)?\s*\(', masked(production))]
        result.append({'path':path,'sha256':hashlib.sha256(text.encode()).hexdigest(),'lines':len(text.splitlines()),'production_function_declarations':symbols})
    return result

def test_inventory():
    result = []
    # Existing test locations, not a claim all cfg/platform branches compile.
    for package in ['tidb-expr','tidb-datatype','tidb-codec','tidb-executor','tidb-planner','tidb-session','tidb-exec','tidb-unistore']:
        prefix = 'rust/crates/' + package + '/'
        manifest = tomllib.loads(source(prefix+'Cargo.toml'))
        explicit = {prefix+t['path']:t['name'] for t in manifest.get('test',[]) if 'path' in t}
        paths = [p for p in files(prefix) if p.endswith('.rs') and ('/src/' in p or '/tests/' in p)]
        top = [p for p in paths if p.startswith(prefix+'tests/') and '/' not in p[len(prefix+'tests/'):]]
        top_texts = {p:source(p) for p in top}
        referenced = {p for p in top if any('#[path = "'+Path(p).name+'"]' in text for text in top_texts.values())}
        aggregated = {p for p in top if Path(p).name!='all.rs' and p not in referenced and 'aggregate-test: standalone' not in top_texts[p]} if manifest.get('package',{}).get('build')=='../../scripts/aggregate-tests.rs' else set()
        for path in paths:
            text = source(path)
            if '#[test]' not in text and '#[tokio::test' not in text: continue
            test_rx = re.compile(r'#\[(?:test|tokio::test[^\]]*)\](?:\s*#\[[^\]]*\])*\s*(?:pub\s+)?(?:async\s+)?fn\s+(\w+)')
            tests = [{'name':m[1], 'line':text[:m.start()].count('\n')+1, 'ignored_after_test_attribute':bool(re.search(r'#\[ignore',m[0]))} for m in test_rx.finditer(text)]
            if not tests: continue
            is_integration = path.startswith(prefix+'tests/')
            targets = [] if is_integration else ['lib']
            if path in aggregated: targets.append('all')
            if path in explicit: targets.append(explicit[path])
            stem = Path(path).stem
            result.append({'repo':'tidb','path':path,'package':package,'targets':targets,'module_filter': stem+'::' if path in aggregated else None,
                'test_declaration_count':len(tests),'ignored_after_test_attribute_count':sum(t['ignored_after_test_attribute'] for t in tests),'tests':tests,
                'evidence':'static literal declarations only; helper module linkage/cfg/ignore-before-test/runtime matching may require discovery; empty targets denotes helper/nested module, not automatically runnable'})
    for package in ['tidb_query_expr','tidb_query_datatype']:
        prefix = 'components/'+package+'/'
        source(prefix+'Cargo.toml','tikv')
        for path in files(prefix+'src/','tikv'):
            if not path.endswith('.rs'): continue
            text = source(path,'tikv')
            tests = [{'name':m[1],'line':text[:m.start()].count('\n')+1} for m in re.finditer(r'#\[test\](?:\s*#\[[^\]]*\])*\s*fn\s+(\w+)',text)]
            if tests:
                result.append({'repo':'tikv','path':path,'package':package,'targets':['lib'],'module_filter':None,'test_declaration_count':len(tests),'tests':tests,'evidence':'literal test declarations only; macro-expanded test cases not enumerated'})
    return result

def function_extent(path, symbol):
    try:
        block, first = body(path, symbol)
        return {'path':path,'symbol':symbol,'start_line':first,'end_line':first+block.count('\n'),'sha256':hashlib.sha256(block.encode()).hexdigest()}
    except ValueError:
        return {'path':path,'symbol':symbol,'extent_unresolved':True}

def generate():
    reg, found = candidates()
    for name, refs in MANUAL.items():
        for file, fn, line in refs:
            found[name].append({'name':name,'path':EXPR+file,'symbol':fn,'line':line,'manual_syntax_or_binding':True})
    # Synthetic names are a finite typed target/domain list, never extra count.
    cast_names = set()
    for short in ['func.rs','scalar_function.rs','rewriter/result_type.rs','aggregation/wrap_cast.rs','builtin_arithmetic.rs']:
        cast_names.update(re.findall(r'"(cast_[a-z_]+)"', clean_comments(source(EXPR+short))))
    pb, native = signatures()
    unknown = {d['family'] for d in [*pb.values(),*native.values()]} - set(found)
    if unknown: raise ValueError('unmapped PB families: '+repr(sorted(unknown)))
    tests = test_inventory()
    rows = []
    for name in sorted(found):
        refs = found[name]
        names = {r['name'] for r in refs} | {n for n in reg if canonical(n)==name}
        if name == 'cast': names |= cast_names
        category = profile(name)
        status = 'host_only' if name in HOST else ('compatibility_stub' if name == 'load_file' else 'implemented_pure_or_contextual')
        entrypoints = set()
        for ref in refs:
            if ref['path'].endswith('scalar_function.rs'): entrypoints.add('typed_row')
            elif ref['path'].endswith('time_literal.rs'): entrypoints.add('rewrite_time_computation')
            elif ref['path'].endswith('lib.rs'): entrypoints.add('ast')
            elif not ref['path'].endswith('rewriter.rs'): entrypoints.update(['shared_value_dispatch','ast_or_typed_callers'])
        pbs = sorted(sig for sig, data in pb.items() if data['family']==name)
        natives = sorted(sig for sig, data in native.items() if data['family']==name)
        if pbs: entrypoints.update(['pb_typed','unistore_shared'])
        if any(sig not in pb for sig in natives): entrypoints.add('unistore_SimpleSig')
        source_refs = sorted({ref['path'] for ref in refs} | {EXPR+p for p in PROFILES[category]['sources']})
        # Exact name-token appearances in expression tests are navigation links,
        # not positive assertions that every named family succeeded.
        test_refs = []
        rx = re.compile(r'(?i)(?<![A-Za-z0-9_])(?:'+ '|'.join(re.escape(n) for n in sorted(names)) + r')(?![A-Za-z0-9_])')
        for file in tests:
            if file['package'] != 'tidb-expr': continue
            text = source(file['path'])
            if '/src/' in file['path'] and '/tests/' not in file['path']:
                test_at = text.find('#[cfg(test)]')
                if test_at < 0: continue
                text = text[test_at:]
            if rx.search(text): test_refs.append(file['path'])
        rows.append({
            'id':name,'classification':status,'in_denominator':status=='implemented_pure_or_contextual',
            'spellings_and_synthetic_variants':sorted(names),'category':category,
            'registry_arities':{n:reg[n] for n in sorted(names) if n in reg},
            'dispatch_evidence':refs,'native_source_paths':source_refs,'domain_profile':category,
            'supported_overload_evidence':{'typed_pb_signatures':pbs,'unistore_converter_signatures':natives,
                'sql_ast_arity_and_guard_definition':'Referenced dispatch clauses and fixed-SHA function extents; registration arity alone is NOT an accepted domain.',
                'exact_domain_definition':'The executable branches at the fixed baseline sources, including existing Unsupported/NULL/error behavior. Profiles summarize, not replace this intensional definition.'},
            'entrypoints_with_static_evidence':sorted(entrypoints),
            'consumer_obligation':'All consumer entrypoints that reach this family, including folding/default/DML/join/aggregate/window helpers; no runtime origin instrumentation performed.',
            'existing_test_source_links':test_refs,'test_link_strength':'lexical navigation only, not passed/positive/full-domain coverage',
            'domain_notes':NOTES.get(name), 'exclusion_reason':HOST.get(name) if name in HOST else (NOTES[name] if status=='compatibility_stub' else None),
            'unresolved_domains':['per-overload input/type/collation/context Cartesian matrix not executed','TiKV compatibility and execution-origin/deletion proof not established'],
            'migration_state':'not_migrated_baseline','intended_owner':'TiDB host/binding' if name in HOST else 'TiKV unique kernel; exact host subdomains explicitly separated',
            'deletion_map_ids':['ast_dispatch','typed_dispatch','pb_kernel','batch_filter','unistore_native','shared_primitives','construction_and_consumers', 'native_ops_cast' if category in {'operator_numeric','comparison','control','cast'} else 'native_families'],
        })
    missing = {n for n in reg if canonical(n) not in found}
    assert missing == set(UNIMPLEMENTED), (missing-set(UNIMPLEMENTED),set(UNIMPLEMENTED)-missing)
    sigrows = [{'signature':sig,'family':pb_family(sig),'pb_builtin':pb.get(sig),'unistore_converter':native.get(sig)} for sig in sorted(set(pb)|set(native))]
    counts = collections.Counter(r['classification'] for r in rows)
    denominator = counts['implemented_pure_or_contextual']
    source_catalog = source_inventory()
    data = {
        'schema_version':1,'inventory_revision':'M0-static-v1','purpose':'Frozen evidence, not a second plan; no product code/build/test execution in this task.',
        'baseline':{r:{'worktree':str(ROOT/r),'sha':sha} for r,sha in SHA.items()},
        'authority':'Only fixed Git objects from the new approved worktrees; old expression-reuse trees not inspected or used.',
        'methodology':{
            'unit':'One logical function/operator/explicit AST computation family after documented alias/synthetic-overload normalization.',
            'counting':'One family across AST/typed/PB/batch/helper/cop paths. Cast source-target and date-unit signatures are overloads, not separate counts. Whole supported baseline domain required for full migration.',
            'exclusions':'Host-only/binding/type-metadata primitives, constant leaves, structural ROW, unavailable/never-implemented registry names and LOAD_FILE always-NULL compatibility stub.',
            'conservative_mixed_policy':'RAND (including dynamic deterministic seed), clocks/NOW/UTC/SYSDATE, TIDB_BOUNDED_STALENESS, UNIX_TIMESTAMP, JSON_SCHEMA_VALID and VALIDATE_PASSWORD_STRENGTH retain counted pure domains with explicit host subdomains; context sensitivity never automatically excludes a family.',
            'static_evidence_limit':'Source admission/dispatch/definition and test declarations only. No builds, Cargo metadata, test runs or exhaustive domain/oracle measurements. Lexical links are not test coverage.',
            'alias_rules':ALIASES,
            'negated_syntax_rule':'NOT IN/BETWEEN/LIKE/IS forms retain negative variant domain under base family plus NOT operator; variants are not asserted identical results.',
            'provenance':'Generator reads SHA:path Git objects, so concurrent edits by implementation agents cannot silently redefine baseline.',
        },
        'counts':{'registry_literal_names':len(reg),'registry_comment_claim':309,'family_rows':len(rows),'denominator':denominator,
                  'minimum_complete_for_90_percent':(denominator*90+99)//100,'classifications':dict(counts),
                  'registry_names_without_runtime_dispatch':len(missing),'typed_pb_signatures':len(pb),
                  'typed_pb_cast_signatures':sum(s.startswith('Cast') for s in pb),
                  'unistore_converter_signatures':len(native),'pb_native_intersection':len(set(pb)&set(native)),
                  'typed_pb_only_signatures':len(set(pb)-set(native)),'unistore_only_signatures':len(set(native)-set(pb)),
                  'union_signature_admission':len(set(pb)|set(native)),'known_unistore_admitted_but_None_domains':sum(d['implementation_status']=='explicit_None_result_gap' for d in native.values()),
                  'runtime_verified_families':0,'migrated_families':0},
        'families':rows,'registry_only_or_syntax_rows':[{'name':n,'arity':reg[n],'classification':UNIMPLEMENTED[n][0],'evidence':UNIMPLEMENTED[n][1],'in_denominator':False} for n in sorted(missing)],
        'ast_forms':AST_FORMS,'domain_profiles':PROFILES,
        'syntax_aliases':{'plus':['+'],'minus':['- (binary)'],'mul':['*'],'div':['/'],'intdiv':['DIV'],'mod':['MOD','%'],'eq':['='],'ne':['!=','<>'],'lt':['<'],'le':['<='],'gt':['>'],'ge':['>='],'nulleq':['<=>'],'and':['AND','&&'],'or':['OR','|| under ordinary SQL mode'],'xor':['XOR'],'not':['NOT','!'],'bitand':['&'],'bitor':['|'],'bitxor':['^'],'bitneg':['~'],'leftshift':['<<'],'rightshift':['>>'],'unaryplus':['+ (unary)'],'unaryminus':['- (unary)'],'char_func':['CHAR(...)'],'insert_func':['INSERT(...)'],'cast':['CAST(... AS type)','CONVERT(..., type)','BINARY expr'],'convert_charset':['CONVERT(... USING charset)'],'json_member_of':['MEMBER OF']},
        'collation_domain_catalog':{'path':'rust/crates/tidb-datatype/src/collation.rs:204-235',
            'registered_but_unimplemented':['utf8mb4_zh_pinyin_tidb_as_cs: compare/key operations panic implement me at609-704; catalog presence is NOT a supported computation domain'],

            'new_mode_names':['binary','ascii_bin','latin1_bin','utf8_bin','utf8_general_ci','utf8_unicode_ci','utf8mb4_bin','utf8mb4_general_ci','utf8mb4_unicode_ci','utf8mb4_0900_ai_ci','utf8mb4_0900_bin','utf8mb4_zh_pinyin_tidb_as_cs','gbk_bin','gbk_chinese_ci','gb18030_bin','gb18030_chinese_ci'],
            'legacy':'DerivedBinary when use_new_collation=false; unknown new name falls back utf8mb4_bin.',
            'limit':'Catalog presence is not each-expression support; PAD SPACE/no-pad/key/LIKE bytes/runes and invalid octets are per-operation domains. Signed wire IDs must not be absolutized.'},
        'pb_and_unistore':{'signatures':sigrows,'native_enum_variants':163,'routing_evidence':'cophandler.rs:2077-2082 supports_signature -> convert_shared before native converter; pb_to_expr recursively requires its supported child signatures.',
            'native_domain_gap':'8 Duration*Datetime AddDate/SubDate variants explicitly return None in eval_time; retain as admitted but not implemented, not successful overload coverage.',
            'family_count_effect':'No extra logical families from PB-only IDs; retain every signature as a separate domain obligation under existing families.',
            'native_value_error_channels':'eval_decimal/json/real/duration/time/bytes invoke eval_shared(...).ok()? at2704/2870/3055/3423/3543/3793, swallowing child errors as None; other native integer arms can swallow Err too.',
            'consumer_restrictions':'eval_datum:1248-1267 and TopNSpec::evaluate:1348-1350 reject Func but allow Shared. RegionAggregator args build through converter:1033 and use eval_datum:1114. Group-by remains Column-only:1008-1009.',
            'literal_domains':'Native top-level decoder7 literals+ColumnRef; shared11+ColumnRef adds Uint64,Bytes,Float32,MysqlDuration. Native Float64 reads raw bits at2091-2100 while shared uses decode_float at distsql_builtin.rs:77-79.',
            'native_live_variants':61,'shadowed_variants_caveat':'102 wire IDs shadowed by Shared routing remain directly constructible through public SimpleExpr::Func and tests; not globally dead code.',
            'native_deletion_sites':{'definitions':'cophandler.rs:1526-2034','converter':'2073-2682','eval_decimal':'2695-2836','eval_json':'2859-3042','eval_real':'3046-3211','eval_duration':'3414-3530','eval_time':'3534-3680','eval_bytes':'3784-4049','native_Func_dispatch':'4154-5053','date_helpers':'3219-3412','other_helpers':'1180-1246,2841-2858,3688-3783'},
            'prune_order':'After102 shadowed mappings/arms retire, go_float_display/datum_to_json_value/conv_convert/valid_prefix/format_u64_base and regexp-only regex use are candidate dead code; date helpers and numeric_prefix remain for native-only domains. collation_of remains a TopN consumer.'},

        'entrypoints':ENTRYPOINTS,'native_deletion_map':DELETION_MAP,'native_source_inventory':source_catalog,
        'dispatch_function_extents':[function_extent(EXPR+p,fn) for p,fns in DISPATCH.items() for fn in fns],
        'existing_tests':tests,'suggested_test_commands':test_commands(),
        'reported_parent_baseline_runs':[
            {'suite':'tidb_query_datatype collation','result':'8 passed,0 failed,294 filtered','log':'/home/agent/tidb/expression-unification/logs/tikv-collation-baseline-native-compat.log:33','evidence':'Parent reports source-clean original TiKV; Validation E read summary. Parent owns exact native-build environment.'},
            {'suite':'tidb_query_expr full lib','result':'428 passed,0 failed,0 filtered','log':'/home/agent/tidb/expression-unification/logs/tikv-expr-baseline.log:483','evidence':'Parent reports source-clean original TiKV; Validation E read summary.'},
            {'suite':'tidb_query_datatype codec::mysql::decimal::tests','result':'26 passed,0 failed,276 filtered','log':'/home/agent/tidb/expression-unification/logs/tikv-decimal-baseline.log:34','evidence':'Parent reports source-clean original TiKV; Validation E read all26 test names/summary. No cross-repository Decimal-domain parity inferred.'},
            {'command':'tools/cargo-tidb test --locked -p tidb-datatype --lib collation -- --test-threads=1','result':'25 passed, 0 failed, 402 filtered','log':'/home/agent/tidb/expression-unification/logs/tidb-datatype-collation-baseline.log:92','evidence':'Parent executed; Validation E read final result.'},
            {'command':'tools/cargo-tidb test --locked -p tidb-datatype --test all collation_sort_keys_match_go_byte_for_byte -- --test-threads=1','result':'1 passed, 0 failed, 66 filtered','log':'/home/agent/tidb/expression-unification/logs/tidb-go-collation-baseline.log:23','evidence':'Parent executed; Validation E read final result.'},
            {'command':'tools/cargo-tidb test --locked -p tidb-expr --lib -- --test-threads=1','result':'1226 passed, 4 failed, 93 ignored, 1323 discovered','log':'/home/agent/tidb/expression-unification/logs/tidb-expr-lib-baseline.log:2078-2112','failures':['pushdown_catalog::tests::ifnull_string_column_literal_uses_go_signature_and_column_collation','tests::builtin_info_json_math_source::exp','tests::builtin_math_misc_op_source::vectorized_builtin_op_func','time_fn::tests::str_to_date_partial_formats_follow_no_zero_date'],'evidence':'Parent executed before algorithm changes; Validation E read failure assertions. Parent reports all four independently reproduced with exit 101; not a migration regression.'}
        ],
        'unresolved_evidence':[
            {'id':'domain_matrix','affects':'every family','status':'unresolved','detail':'Static source gives an exact baseline domain definition but no executed cross-product. Family counts must not be reported as domain coverage.'},
            {'id':'ast_logic_demand','affects':['and','or'],'status':'source_proven_difference_runtime_unverified','detail':'eval_in binary eager; ScalarFunction/PB lazy. Proposed dead-branch probes are 0 AND (\'x\' REGEXP \'[\') and 1 OR (\'x\' REGEXP \'[\'). Avoid folding confound by building typed nodes without fold.'},
            {'id':'pb_native_tree_closure','affects':'PB/un istore recursive trees','status':'source_proven_limit','detail':'245-ID union only single-node admission; shared parent + native-only child is not accepted recursively.'},
            {'id':'admitted_datetime_gap','affects':'8 date-add/sub Duration*Datetime IDs','status':'source_proven_unimplemented_domain','detail':'eval_time returns None; no success claim for converter acceptance.'},
            {'id':'synthetic_api_reachability','affects':['json_sum_crc32','cast','extract','unaryplus'],'status':'public AST/helper or synthetic builder domain distinguished','detail':'Name availability does not imply SQL parser/rewriter reaches the same path; explicit ARRAY/TimeLiteral gaps recorded.'},
            {'id':'tests','affects':'all','status':'not_run','detail':'Static declarations/filters only. Main agent owns all heavy builds and baseline runtime capture.'},
            {'id':'deletion_and_origin','affects':'all','status':'not_yet_verified','detail':'Map lists baseline algorithms to delete after compatibility; no native deletions or TiKV integration performed by this inventory task.'},
        ],
    }
    # The deterministic RNG algorithm is an external pure subkernel of RAND.
    source('rust/crates/tidb-util/src/mathutil/rand.rs')
    # Include all input hashes consumed by the generator for reproducibility.
    data['input_source_sha256'] = {repo+'/'+path:hashlib.sha256(text.encode()).hexdigest() for (repo,path),text in sorted(CACHE.items())}
    return compact_ledger(data,reg)

def compact_ledger(data,reg):
    """Share repeated source/test/default evidence; preserve exact frozen facts."""
    data['registry'] = reg
    sites, index = [], {}
    test_ids = {t['path']:'T'+str(i+1).zfill(4) for i,t in enumerate(data['existing_tests'])}
    for test in data['existing_tests']:
        test['id']=test_ids[test['path']]
        test['test_sites']=[[t['name'],t['line'],t.get('ignored_after_test_attribute',False)] for t in test.pop('tests')]
    contract_keys=['consumer_obligation','test_link_strength','unresolved_domains','migration_state']
    data['family_row_defaults'] = {k:data['families'][0][k] for k in contract_keys}
    data['family_row_defaults']['supported_domain_contract'] = data['families'][0]['supported_overload_evidence']['exact_domain_definition']
    data['family_row_defaults']['arity_contract'] = data['families'][0]['supported_overload_evidence']['sql_ast_arity_and_guard_definition']
    for row in data['families']:
        for key in contract_keys: row.pop(key)
        row['registry_names'] = list(row.pop('registry_arities'))
        row['dispatch_site_ids']=[]
        for site in row.pop('dispatch_evidence'):
            key=json.dumps(site,sort_keys=True)
            if key not in index:
                index[key]='S'+str(len(sites)+1).zfill(4)
                sites.append({'id':index[key],**site,'source_line':source(site['path']).splitlines()[site['line']-1].strip()})
            row['dispatch_site_ids'].append(index[key])
        row['test_module_ids']=[test_ids[p] for p in row.pop('existing_test_source_links')]
        row.pop('native_source_paths') # union of dispatch site paths and domain_profile.sources
        row['native_source_rule']='Union of dispatch site paths and shared domain_profile.sources; fixed SHA input hashes retained.'
        row['supported_overload_evidence'].pop('exact_domain_definition')
        row['supported_overload_evidence'].pop('sql_ast_arity_and_guard_definition')
        if row['exclusion_reason'] is None: row.pop('exclusion_reason')
        if row['domain_notes'] is None: row.pop('domain_notes')
    data['dispatch_sites']=sites
    return data

def serialize(data):
    # Tables get one complete JSON row per line; profiles/definitions remain
    # conventionally indented. This is ordinary parseable JSON, not JSONL.
    tables={'families','dispatch_sites','existing_tests','native_source_inventory','dispatch_function_extents','suggested_test_commands'}
    parts=[]
    for key,value in data.items():
        if key in tables:
            encoded='[\n'+',\n'.join('    '+json.dumps(v,ensure_ascii=False,separators=(',', ':')) for v in value)+'\n  ]'
        else:
            encoded=json.dumps(value,indent=2,ensure_ascii=False).replace('\n','\n  ')
        parts.append('  '+json.dumps(key)+': '+encoded)
    return '{\n'+',\n'.join(parts)+'\n}\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--draft', action='store_true')
    parser.add_argument('--check', action='store_true', help='Regenerate in memory and check existing JSON without writing.')
    opts = parser.parse_args()
    if opts.draft:
        reg, found = candidates()
        print('registry names:',len(reg),'candidate families:',len(found))
        print('candidates:',' '.join(sorted(found)))
        print('registry without extracted candidate:',' '.join(sorted(n for n in reg if canonical(n) not in found)))
    else:
        data = generate()
        output = ROOT/'evidence/coverage-baseline.json'
        text = serialize(data)
        if opts.check:
            assert output.read_text() == text, 'Existing evidence differs from deterministic regeneration'
        else:
            output.write_text(text)
        print(json.dumps(data['counts'],indent=2))
